core/urls.py
from django.contrib import admin
from django.urls import path
import core.views

app_name = 'core'

urlpatterns = [
    path('', core.views.IndexView.as_view(), name='index'),
    path('books/', core.views.Books.as_view(), name='book_list'),
    path('books/<int:pk>/', core.views.BookDetail.as_view(), name='book_detail'),
    path('books/create/', core.views.BookCreate.as_view(), name='book_create'),
    path('books/<int:pk>/update/', core.views.BookUpdate.as_view(), name='book_update'),
    path('books/<int:pk>/delete/', core.views.BookDelete.as_view(), name='book_delete'),

]

project/urls.py
import os

from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include
from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]
if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=os.path.join(settings.BASE_DIR, 'node_modules'))

core/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    name = models.CharField('Имя', max_length=128)

    # def __str__(self):
    #     return self.name


class AuthorProfile(models.Model):
    author = models.OneToOneField


class Book(models.Model):
    author = models.ForeignKey('core.Author', on_delete=models.CASCADE, null=True, blank=True, related_name='books')
    name = models.CharField('Название', max_length=128)
    pages = models.IntegerField('Количество страниц', blank=True, null=True)

    class Meta:
        ordering = ['pages']
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        if True:
            return self.name
        else:
            return 'Kek'


class Order(models.Model):
    date = models.DateField()
    book = models.ManyToManyField('core.Book')

core/forms.py
from django import forms

import core.models


class BookSearch(forms.Form):
    name = forms.CharField(label='Название', required=False)
    pages = forms.IntegerField(label='Кол-во страниц', required=False, help_text='Минимальное количество страниц')
    author = forms.ModelChoiceField(label='Автор', queryset=core.models.Author.objects.all(), to_field_name='name')

    def clean(self):
        pages = self.cleaned_data.get('pages')

        if pages and pages > 1000:
            raise forms.ValidationError('Количество страниц не может быть больше 1000')

        return pages



class BookEdit(forms.ModelForm):
    class Meta:
        model = core.models.Book
        fields = '__all__'

core/views.py
from django.http import HttpResponseNotFound
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView

import core.models
import core.forms
import core.filters


class TitleMixin:
    title: str = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = self.get_title()
        return context


class IndexView(TitleMixin, TemplateView):
    template_name = 'core/index.html'
    title = 'Главная страница'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['info'] = self.get_info()
        return context

    def get_info(self):
        return 'Главная страница'


class Books(TitleMixin, ListView):
    title = 'Книги'

    def get_filters(self):
        return core.filters.BookFilter(self.request.GET)

    def get_queryset(self):
        # name = self.request.GET.get('name')
        # queryset = core.models.Book.objects.all()
        # if name:
        #     queryset = queryset.filter(name__icontains=name)
        # return queryset
        return self.get_filters().qs

    def get_context_data(self):
        context = super().get_context_data()
        context['form'] = core.forms.BookSearch(self.request.GET or None)
        #context['filters'] = self.get_filters()
        return context


class BookDetail(TitleMixin, DetailView):
    queryset = core.models.Book.objects.all()

    def get_title(self):
        return str(self.get_object())


class BookUpdate(TitleMixin, UpdateView):
    model = core.models.Book
    form_class = core.forms.BookEdit

    def get_title(self):
        return f'Изменение данных книги "{str(self.get_object())}"'

    def get_success_url(self):
        return reverse('core:book_list')


class BookCreate(TitleMixin, CreateView):
    model = core.models.Book
    form_class = core.forms.BookEdit
    title = 'Добавление книги'

    def get_success_url(self):
        return reverse('core:book_list')


class BookDelete(TitleMixin, DeleteView):
    model = core.models.Book

    def get_title(self):
        return f'Удаление книги {str(self.get_object())}'

    def get_success_url(self):
        return reverse('core:book_list')
    #14:10
    # Create your views here.

core/templates/core/book_confirm_delete.html
{% extends 'core/index.html' %}
{% load bootstrap5 %}

{% block content %}
    <div class="alert alert-danger">
        Вы действительно хотите удалить книгу "{{ object }}"
    </div>

    <form method="post">{% csrf_token %}
        <button type="submit" class="btn btn-danger">
            Да
        </button>
        <a href="{% url 'core:book_list' %}" class="btn btn-success"> Нет</a>
    </form>
{% endblock %}

core/templates/core/book_detail.html
{% extends 'core/index.html' %}
{% block content %}
    <a href="{% url 'core:book_update' object.pk %}">Изменить</a>
    <a href="{% url 'core:book_delete' object.pk %}">Удалить</a>
{% endblock %}

core/templates/core/book_form.html
{% extends 'core/index.html' %}
{%  load bootstrap5 %}

{% block content %}
<form class="row g-3" method="post">{% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="col-auto">
        <button type="sumbit" class="btn btn-primary mb-3">Сохранить</button>
    </div>
</form>

{% endblock %}

core/templates/core/book_list.html
  {% extends 'core/index.html' %}



  {% block content %}
  {% include 'core/search_books_include.html' %}

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Название</th>
          <th scope="col">Количество страниц</th>
        </tr>
      </thead>
      <tbody>
      {% for book in object_list %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'core:book_detail' book.pk %}">{{book.name|capfirst}}</a></td>
          <td>{{book.pages|default:"-"}}</td>
        </tr>
      {% empty %}
        <h4>Не найдено</h4>
      {% endfor %}
      </tbody>
    </table>

    <a href="{% url 'core:book_create' %}" class="btn btn-success"> Добавить книгу</a>

    {% endblock %}

core/templates/core/index.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="admin/">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:book_list' %}">Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    {% block title %}
      {% if title %}
        <h3>{{ title }}</h3>
      {% endif %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    <script src="/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
  </body>
</html>

core/templates/core/search_books_include.html
{% load bootstrap5 %}
<form class="row g-3">
    <!--<div class="col-auto">
        <input type="text" class="form-control" placeholder="Название" name="name" value="{{ request.GET.name }}">
    </div>-->
    {% bootstrap_form form layout='horizontal' %}
{#    {% bootstrap_form filters.form layout='horizontal'%}#}
    <div class="col-auto">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>